-- Ammo Inventory Manager V2.1 - Supabase/PostgreSQL schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null default 'READONLY' check (role in ('ADMIN','SUPERVISOR','ARMORER','READONLY')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.products (
  id bigint generated by default as identity primary key, manufacturer text not null, caliber text not null,
  load_name text not null, bullet_weight text default '', upc text unique, sku text default '',
  rounds_per_box int not null check(rounds_per_box>0), category text not null default 'Training',
  reorder_threshold int not null default 0 check(reorder_threshold>=0), created_at timestamptz not null default now()
);
create table if not exists public.ammo_lots (
  id bigint generated by default as identity primary key, product_id bigint not null references public.products(id),
  lot_number text not null, received_date date not null default current_date, vendor text default '', purchase_order text default '',
  recalled boolean not null default false, recall_note text default '', created_at timestamptz not null default now(), unique(product_id,lot_number)
);
create table if not exists public.locations (id bigint generated by default as identity primary key, name text not null unique);
create table if not exists public.personnel (id bigint generated by default as identity primary key, name text not null, badge_id text default '', assignment text default '', active boolean not null default true);
create table if not exists public.inventory_balance (
  product_id bigint not null references public.products(id), lot_id bigint not null references public.ammo_lots(id),
  location_id bigint not null references public.locations(id), current_qty int not null default 0 check(current_qty>=0), primary key(product_id,lot_id,location_id)
);
create table if not exists public.transactions (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  txn_type text not null check(txn_type in ('RECEIVE','ISSUE','RETURN','TRANSFER','ADJUST','COUNT')),
  product_id bigint not null references public.products(id), lot_id bigint references public.ammo_lots(id),
  quantity_rounds int not null check(quantity_rounds>0), signed_delta int not null default 0,
  from_location_id bigint references public.locations(id), to_location_id bigint references public.locations(id),
  personnel_id bigint references public.personnel(id), reason text not null default '', notes text default '',
  created_by_user_id uuid references public.profiles(id), created_by text not null default '', approval_id bigint
);
create table if not exists public.adjustment_requests (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  product_id bigint not null references public.products(id), lot_id bigint not null references public.ammo_lots(id),
  location_id bigint not null references public.locations(id), delta_rounds int not null check(delta_rounds<>0),
  reason text not null, notes text default '', requested_by_user_id uuid not null references public.profiles(id),
  status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),
  reviewed_at timestamptz, reviewed_by_user_id uuid references public.profiles(id), review_note text default ''
);
create table if not exists public.inventory_counts (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  product_id bigint not null references public.products(id), lot_id bigint not null references public.ammo_lots(id),
  location_id bigint not null references public.locations(id), expected_rounds int not null, counted_rounds int not null,
  variance_rounds int not null, reason text not null default 'Physical inventory', counted_by_user_id uuid not null references public.profiles(id),
  adjustment_request_id bigint references public.adjustment_requests(id)
);
create table if not exists public.audit_events (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  user_id uuid references public.profiles(id), event_type text not null, entity_type text default '', entity_id bigint, detail text default ''
);

create or replace function public.my_role() returns text language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() and active=true $$;
create or replace function public.my_name() returns text language sql stable security definer set search_path=public as $$ select display_name from profiles where id=auth.uid() $$;
create or replace function public.can_write() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(my_role() in ('ADMIN','SUPERVISOR','ARMORER'),false) $$;
create or replace function public.can_review() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(my_role() in ('ADMIN','SUPERVISOR'),false) $$;

alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.ammo_lots enable row level security;
alter table public.locations enable row level security; alter table public.personnel enable row level security; alter table public.inventory_balance enable row level security;
alter table public.transactions enable row level security; alter table public.adjustment_requests enable row level security; alter table public.inventory_counts enable row level security; alter table public.audit_events enable row level security;

-- Authenticated users may read operational data. Direct writes are intentionally blocked; RPC functions below enforce roles and atomicity.
create policy "profiles self/read" on public.profiles for select to authenticated using (true);
create policy "products read" on public.products for select to authenticated using (true);
create policy "lots read" on public.ammo_lots for select to authenticated using (true);
create policy "locations read" on public.locations for select to authenticated using (true);
create policy "personnel read" on public.personnel for select to authenticated using (true);
create policy "inventory read" on public.inventory_balance for select to authenticated using (true);
create policy "transactions read" on public.transactions for select to authenticated using (true);
create policy "adjustments read" on public.adjustment_requests for select to authenticated using (can_review() or requested_by_user_id=auth.uid());
create policy "counts read" on public.inventory_counts for select to authenticated using (true);
create policy "audit review" on public.audit_events for select to authenticated using (can_review());

create or replace function public.audit(p_event text,p_entity text default '',p_entity_id bigint default null,p_detail text default '') returns void
language plpgsql security definer set search_path=public as $$ begin insert into audit_events(user_id,event_type,entity_type,entity_id,detail) values(auth.uid(),p_event,p_entity,p_entity_id,p_detail); end $$;

create or replace function public.add_product(p_manufacturer text,p_caliber text,p_load_name text,p_bullet_weight text,p_upc text,p_sku text,p_rounds_per_box int,p_category text,p_reorder_threshold int)
returns bigint language plpgsql security definer set search_path=public as $$ declare rid bigint; begin if not can_write() then raise exception 'Insufficient permission'; end if;
insert into products(manufacturer,caliber,load_name,bullet_weight,upc,sku,rounds_per_box,category,reorder_threshold) values(trim(p_manufacturer),trim(p_caliber),trim(p_load_name),coalesce(p_bullet_weight,''),nullif(trim(p_upc),''),coalesce(p_sku,''),p_rounds_per_box,coalesce(p_category,'Training'),coalesce(p_reorder_threshold,0)) returning id into rid; perform audit('PRODUCT_CREATED','product',rid,''); return rid; end $$;

create or replace function public.add_lot(p_product_id bigint,p_lot_number text,p_received_date date,p_vendor text default '',p_purchase_order text default '') returns bigint
language plpgsql security definer set search_path=public as $$ declare rid bigint; begin if not can_write() then raise exception 'Insufficient permission'; end if;
select id into rid from ammo_lots where product_id=p_product_id and lot_number=trim(p_lot_number); if rid is null then insert into ammo_lots(product_id,lot_number,received_date,vendor,purchase_order) values(p_product_id,trim(p_lot_number),coalesce(p_received_date,current_date),coalesce(p_vendor,''),coalesce(p_purchase_order,'')) returning id into rid; perform audit('LOT_CREATED','lot',rid,''); end if; return rid; end $$;

create or replace function public.inventory_txn(p_kind text,p_product_id bigint,p_lot_id bigint,p_quantity int,p_from bigint default null,p_to bigint default null,p_personnel bigint default null,p_reason text default '',p_notes text default '') returns jsonb
language plpgsql security definer set search_path=public as $$ declare have int:=0; uname text:=my_name(); tid bigint; delta int:=0; begin
if not can_write() then raise exception 'Insufficient permission'; end if; if p_quantity<=0 then raise exception 'Quantity must be positive'; end if;
if p_kind='RECEIVE' or p_kind='RETURN' then if p_to is null then raise exception 'Destination required'; end if; insert into inventory_balance values(p_product_id,p_lot_id,p_to,0) on conflict do nothing; update inventory_balance set current_qty=current_qty+p_quantity where product_id=p_product_id and lot_id=p_lot_id and location_id=p_to; delta:=p_quantity;
elsif p_kind='ISSUE' then select coalesce(current_qty,0) into have from inventory_balance where product_id=p_product_id and lot_id=p_lot_id and location_id=p_from for update; if p_quantity>have then raise exception 'Invalid quantity. Available: %',have; end if; update inventory_balance set current_qty=current_qty-p_quantity where product_id=p_product_id and lot_id=p_lot_id and location_id=p_from; delta:=-p_quantity;
elsif p_kind='TRANSFER' then if p_from=p_to then raise exception 'Source and destination must differ'; end if; select coalesce(current_qty,0) into have from inventory_balance where product_id=p_product_id and lot_id=p_lot_id and location_id=p_from for update; if p_quantity>have then raise exception 'Invalid transfer. Available: %',have; end if; update inventory_balance set current_qty=current_qty-p_quantity where product_id=p_product_id and lot_id=p_lot_id and location_id=p_from; insert into inventory_balance values(p_product_id,p_lot_id,p_to,0) on conflict do nothing; update inventory_balance set current_qty=current_qty+p_quantity where product_id=p_product_id and lot_id=p_lot_id and location_id=p_to;
else raise exception 'Unsupported transaction'; end if;
insert into transactions(txn_type,product_id,lot_id,quantity_rounds,signed_delta,from_location_id,to_location_id,personnel_id,reason,notes,created_by_user_id,created_by) values(p_kind,p_product_id,p_lot_id,p_quantity,delta,p_from,p_to,p_personnel,coalesce(p_reason,''),coalesce(p_notes,''),auth.uid(),coalesce(uname,'')) returning id into tid; perform audit(p_kind,'transaction',tid,p_quantity||' rounds'); return jsonb_build_object('ok',true,'id',tid); end $$;

create or replace function public.submit_count(p_product_id bigint,p_lot_id bigint,p_location_id bigint,p_counted int,p_reason text default 'Physical inventory',p_notes text default '') returns jsonb
language plpgsql security definer set search_path=public as $$ declare expected int:=0; variance int; aid bigint:=null; cid bigint; begin if not can_write() then raise exception 'Insufficient permission'; end if; if p_counted<0 then raise exception 'Count cannot be negative'; end if;
select coalesce(current_qty,0) into expected from inventory_balance where product_id=p_product_id and lot_id=p_lot_id and location_id=p_location_id; variance:=p_counted-expected; if variance<>0 then insert into adjustment_requests(product_id,lot_id,location_id,delta_rounds,reason,notes,requested_by_user_id) values(p_product_id,p_lot_id,p_location_id,variance,coalesce(p_reason,'Physical count variance'),coalesce(p_notes,''),auth.uid()) returning id into aid; end if; insert into inventory_counts(product_id,lot_id,location_id,expected_rounds,counted_rounds,variance_rounds,reason,counted_by_user_id,adjustment_request_id) values(p_product_id,p_lot_id,p_location_id,expected,p_counted,variance,coalesce(p_reason,'Physical inventory'),auth.uid(),aid) returning id into cid; perform audit('PHYSICAL_COUNT','count',cid,'variance '||variance); return jsonb_build_object('ok',true,'expected',expected,'counted',p_counted,'variance',variance,'adjustment_request_id',aid); end $$;

create or replace function public.review_adjustment(p_adjustment_id bigint,p_approve boolean,p_review_note text default '') returns jsonb
language plpgsql security definer set search_path=public as $$ declare a adjustment_requests%rowtype; have int:=0; tid bigint; begin if not can_review() then raise exception 'Insufficient permission'; end if; select * into a from adjustment_requests where id=p_adjustment_id and status='PENDING' for update; if not found then raise exception 'Pending request not found'; end if;
if p_approve then select coalesce(current_qty,0) into have from inventory_balance where product_id=a.product_id and lot_id=a.lot_id and location_id=a.location_id for update; if have+a.delta_rounds<0 then raise exception 'Approval would create negative inventory'; end if; insert into inventory_balance values(a.product_id,a.lot_id,a.location_id,0) on conflict do nothing; update inventory_balance set current_qty=current_qty+a.delta_rounds where product_id=a.product_id and lot_id=a.lot_id and location_id=a.location_id; insert into transactions(txn_type,product_id,lot_id,quantity_rounds,signed_delta,from_location_id,to_location_id,reason,notes,created_by_user_id,created_by,approval_id) values('ADJUST',a.product_id,a.lot_id,abs(a.delta_rounds),a.delta_rounds,case when a.delta_rounds<0 then a.location_id end,case when a.delta_rounds>0 then a.location_id end,a.reason,a.notes,auth.uid(),my_name(),a.id) returning id into tid; update adjustment_requests set status='APPROVED',reviewed_at=now(),reviewed_by_user_id=auth.uid(),review_note=coalesce(p_review_note,'') where id=a.id; perform audit('ADJUSTMENT_APPROVED','adjustment',a.id,''); return jsonb_build_object('ok',true,'status','APPROVED');
else update adjustment_requests set status='REJECTED',reviewed_at=now(),reviewed_by_user_id=auth.uid(),review_note=coalesce(p_review_note,'') where id=a.id; perform audit('ADJUSTMENT_REJECTED','adjustment',a.id,''); return jsonb_build_object('ok',true,'status','REJECTED'); end if; end $$;

-- Seed non-sensitive lookup data. Change these after deployment if needed.
insert into public.locations(name) values ('Main Armory'),('Range'),('Patrol Supply'),('SWAT') on conflict do nothing;
insert into public.personnel(name,badge_id,assignment) values ('John Smith','102','Patrol'),('Maria Lopez','118','Training') on conflict do nothing;

-- First admin: after creating the first user in Supabase Authentication, run:
-- insert into public.profiles(id,display_name,role) values ('AUTH-USER-UUID','Administrator','ADMIN');
